### PR TITLE
Nanhandling

### PR DESCRIPTION
**Pull request by ngergihun**
Sorry for taking so long. I messed up my commits and I am still a super noob user of git. Finally, these are the fixes for the nan handling separated from the spectrum module changes.
Contains fixes for the background fitting with nan values as well.

### CODE REVIEW

**Comment by markotoplak** [comment]
PRs should not have merge commits. I could not rebase this one successfully because of binary files (python notebooks).

Therefore I only took your last two commits and put it here. You first two commits ("GwyImage setters...", and "Small but important corrections") were thus not included when this was merged.

Please prepare a clean PR with what this merge is missing. To make it, start from `Quasars/master`, not from `master` from your repository (I see you start here and this makes most of the problems).

**Comment by markotoplak** [comment]
@ngergihun, the original branch you used for this PR is available at https://github.com/markotoplak/pySNOM/tree/nanhandling-backup. You can files from that branch to make a new PR.

**Comment by ngergihun** [comment]
Thx, I do a clean up.

**Comment by ngergihun** [comment]
@markotoplakthe quasars master somehow has all the modifications from the mentioned commits. Thus, you can delete the backup branch, thx.

**Pull request merged**
