### PR TITLE
Nan, inf, division by zero

### PR DESCRIPTION
**Pull request by ngergihun**
Hi Marko! I took your last commit further and made sure all the image transformations handle nan, inf, and zero divisions.
I only tested them one-by-one by hand and looks to work fine.
Also, I removed the direct typecast from the background fit transformer, which was not that nice and corrected the spectrum reader test for the new class structure.

### CODE REVIEW

**Comment by markotoplak** [comment]
Is there really a difference between / and np.divide? If not, keep the simpler one. :)

**Comment by markotoplak** [comment]
So, as far as I know, `np.subtract`== `-` (please correct me if I am incorrect). The difference is in the function that do some aggregates, like mean and nanmean.

**Comment by borondics** [comment]
Both functions have options such as _where_, which could be used for filtering the array for _NaN_, but I guess @ngergihun did not use this option here and the use of `nanmean` works well. 

Any speedup from one or the other approach? I remember that we used `bottleneck.nanmean` in spectroscopy for speedup.

**Comment by markotoplak** [comment]
Forget about bottleneck, that is not our bottleneck. Please avoid it for now.

I think filtering for NaN is not needed - any operation on the NaN is going to yield NaN anyway (which is what we mostly want). So use without `where` is sufficient and thus normal operators are sufficient. 

`nanmean` and company are needed precisely because they make a default where that does not include NaNs, because even a single NaN would screw up the aggregates.

@ngergihun, please start this from scratch and only replace things that are really needed.

**Comment by markotoplak** [comment]
Also, some interferogram file was added here which probably belongs to some other PR. I am closing this one and please open a new PR.

**Comment by ngergihun** [comment]
@markotoplak okay, I revert where we don't need it.

**Pull request closed without merging**
